--
-- PostgreSQL database dump
--

\restrict jaFJpR1cmT0csoeYRVOpT5NZFXiYJ8E1hhtKXaAnrXVdAwIDCfHSpsNs1Fe0It7

-- Dumped from database version 16.11
-- Dumped by pg_dump version 16.11

-- Started on 2026-06-27 12:06:08

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 876 (class 1247 OID 16622)
-- Name: property_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.property_status AS ENUM (
    'AVAILABLE',
    'SOLD',
    'RENTED',
    'PENDING'
);


ALTER TYPE public.property_status OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 230 (class 1259 OID 16632)
-- Name: activity_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activity_history (
    id bigint NOT NULL,
    action_type character varying(255) NOT NULL,
    description text,
    "timestamp" timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.activity_history OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16631)
-- Name: activity_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.activity_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16544)
-- Name: appointments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointments (
    id bigint NOT NULL,
    contact_phone character varying(255),
    message character varying(500),
    request_date timestamp(6) without time zone,
    scheduled_time timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    property_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT appointments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.appointments OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16543)
-- Name: appointments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appointments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16517)
-- Name: properties; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.properties (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(1000),
    location character varying(255),
    price double precision,
    property_type character varying(255),
    title character varying(255),
    user_id bigint,
    contact_number character varying(50),
    full_address character varying(500),
    status character varying(255),
    CONSTRAINT properties_property_type_check CHECK (((property_type)::text = ANY ((ARRAY['SALE'::character varying, 'RENT'::character varying])::text[]))),
    CONSTRAINT properties_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'SOLD'::character varying, 'RENTED'::character varying, 'PENDING'::character varying])::text[])))
);


ALTER TABLE public.properties OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16516)
-- Name: properties_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.properties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.properties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16531)
-- Name: property_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.property_images (
    id bigint NOT NULL,
    image_url character varying(500) NOT NULL,
    is_primary boolean,
    upload_date timestamp(6) without time zone,
    property_id bigint NOT NULL
);


ALTER TABLE public.property_images OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16530)
-- Name: property_images_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.property_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.property_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16494)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16493)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16596)
-- Name: sales; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sales (
    id bigint NOT NULL,
    payment_method character varying(255),
    sale_date timestamp(6) without time zone,
    sale_price double precision NOT NULL,
    status character varying(255),
    buyer_id bigint NOT NULL,
    property_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    CONSTRAINT sales_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.sales OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16595)
-- Name: sales_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16563)
-- Name: transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    payment_method character varying(255),
    payment_status character varying(255),
    price double precision NOT NULL,
    transaction_date timestamp(6) without time zone,
    buyer_id bigint NOT NULL,
    property_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    CONSTRAINT transactions_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);


ALTER TABLE public.transactions OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16562)
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16500)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    is_active boolean,
    name character varying(255),
    password character varying(255),
    role_id bigint,
    created_at timestamp(6) without time zone
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16499)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4804 (class 2606 OID 16638)
-- Name: activity_history activity_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activity_history
    ADD CONSTRAINT activity_history_pkey PRIMARY KEY (id);


--
-- TOC entry 4794 (class 2606 OID 16551)
-- Name: appointments appointments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);


--
-- TOC entry 4790 (class 2606 OID 16524)
-- Name: properties properties_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.properties
    ADD CONSTRAINT properties_pkey PRIMARY KEY (id);


--
-- TOC entry 4792 (class 2606 OID 16537)
-- Name: property_images property_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.property_images
    ADD CONSTRAINT property_images_pkey PRIMARY KEY (id);


--
-- TOC entry 4779 (class 2606 OID 16498)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 4800 (class 2606 OID 16603)
-- Name: sales sales_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT sales_pkey PRIMARY KEY (id);


--
-- TOC entry 4796 (class 2606 OID 16570)
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- TOC entry 4784 (class 2606 OID 16510)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4798 (class 2606 OID 16572)
-- Name: transactions ukc0hf7upiug3ma25o466awtfo9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT ukc0hf7upiug3ma25o466awtfo9 UNIQUE (property_id);


--
-- TOC entry 4781 (class 2606 OID 16508)
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- TOC entry 4802 (class 2606 OID 16605)
-- Name: sales ukqr1d65v7w2saa5dd8ndqonc2x; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT ukqr1d65v7w2saa5dd8ndqonc2x UNIQUE (property_id);


--
-- TOC entry 4786 (class 2606 OID 16506)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4787 (class 1259 OID 16640)
-- Name: idx_property_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_property_status ON public.properties USING btree (status);


--
-- TOC entry 4788 (class 1259 OID 16639)
-- Name: idx_property_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_property_user ON public.properties USING btree (user_id);


--
-- TOC entry 4782 (class 1259 OID 16641)
-- Name: idx_user_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_email ON public.users USING btree (email);


--
-- TOC entry 4810 (class 2606 OID 16583)
-- Name: transactions fk50i2jege2ukupf1ynv0dq6eax; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk50i2jege2ukupf1ynv0dq6eax FOREIGN KEY (seller_id) REFERENCES public.users(id);


--
-- TOC entry 4813 (class 2606 OID 16616)
-- Name: sales fk51eqltjywqvwqy3mjiobehi7s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fk51eqltjywqvwqy3mjiobehi7s FOREIGN KEY (seller_id) REFERENCES public.users(id);


--
-- TOC entry 4814 (class 2606 OID 16611)
-- Name: sales fk6kcwwk044jcrsccvfykxii225; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fk6kcwwk044jcrsccvfykxii225 FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- TOC entry 4808 (class 2606 OID 16557)
-- Name: appointments fk886ced1atxgvnf1o3oxtj5m4s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fk886ced1atxgvnf1o3oxtj5m4s FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4811 (class 2606 OID 16578)
-- Name: transactions fkccxen340nac1r7do7w7g04y5s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkccxen340nac1r7do7w7g04y5s FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- TOC entry 4809 (class 2606 OID 16552)
-- Name: appointments fke32g7ytf1s49sat3w1wm4cptk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fke32g7ytf1s49sat3w1wm4cptk FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- TOC entry 4807 (class 2606 OID 16538)
-- Name: property_images fkemw5i1cysiorfaxfba7tgtpiu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.property_images
    ADD CONSTRAINT fkemw5i1cysiorfaxfba7tgtpiu FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- TOC entry 4812 (class 2606 OID 16573)
-- Name: transactions fkijk7ii2fvalv59schbb3e0bof; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkijk7ii2fvalv59schbb3e0bof FOREIGN KEY (buyer_id) REFERENCES public.users(id);


--
-- TOC entry 4815 (class 2606 OID 16606)
-- Name: sales fkja5sdby5dytewkfletgj235ai; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fkja5sdby5dytewkfletgj235ai FOREIGN KEY (buyer_id) REFERENCES public.users(id);


--
-- TOC entry 4816 (class 2606 OID 16642)
-- Name: activity_history fkn44rak1p4r6f96t2hfeq2a1pc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activity_history
    ADD CONSTRAINT fkn44rak1p4r6f96t2hfeq2a1pc FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4805 (class 2606 OID 16511)
-- Name: users fkp56c1712k691lhsyewcssf40f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- TOC entry 4806 (class 2606 OID 16525)
-- Name: properties fktnyxik10x9mx26017sjnuo2nw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.properties
    ADD CONSTRAINT fktnyxik10x9mx26017sjnuo2nw FOREIGN KEY (user_id) REFERENCES public.users(id);


-- Completed on 2026-06-27 12:06:09

--
-- PostgreSQL database dump complete
--

\unrestrict jaFJpR1cmT0csoeYRVOpT5NZFXiYJ8E1hhtKXaAnrXVdAwIDCfHSpsNs1Fe0It7

